# Generated by Django 4.0.4 on 2022-06-06 22:09

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('forum', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ForumPost',
            new_name='Post',
        ),
    ]
