# Generated by Django 4.0.4 on 2022-06-23 04:14

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('forum', '0003_comment_complaint'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='complaint',
        ),
        migrations.AddField(
            model_name='comment',
            name='complaints',
            field=models.ManyToManyField(related_name='complaints', to=settings.AUTH_USER_MODEL),
        ),
    ]
