# Generated by Django 4.0.4 on 2022-06-28 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0004_remove_comment_complaint_comment_complaints'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='removed',
            field=models.BooleanField(default=False),
        ),
    ]
