# Generated by Django 4.0.4 on 2022-06-30 21:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0005_comment_removed'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='title',
            new_name='tittle',
        ),
    ]
