# Generated by Django 4.0.2 on 2022-07-26 00:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0006_rename_title_post_tittle'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='tittle',
            new_name='title',
        ),
    ]
