# Generated by Django 4.0.2 on 2022-07-31 17:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0004_remove_neighborhood_user'),
        ('forum', '0007_rename_tittle_post_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='neighborhood',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='registration.neighborhood'),
        ),
    ]
