# Generated by Django 4.0.2 on 2022-07-31 17:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0004_remove_neighborhood_user'),
        ('forum', '0008_post_neighborhood'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='neighborhood',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='registration.neighborhood'),
        ),
    ]
