# Generated by Django 4.0.2 on 2022-07-31 18:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0005_alter_neighborhood_description_and_more'),
        ('forum', '0009_alter_post_neighborhood'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='neighborhood',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='registration.neighborhood'),
        ),
    ]
