# Generated by Django 4.0.2 on 2022-08-02 01:45

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0011_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='creationDate',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
