# Generated by Django 4.0.2 on 2022-07-16 02:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profile', '0002_alter_profile_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='profile',
            table='user_profile',
        ),
    ]
