# Generated by Django 4.0.2 on 2022-05-11 01:32

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Neighborhood',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=45)),
                ('shape', django.contrib.gis.db.models.fields.GeometryField(srid=4326)),
                ('is_active', models.SmallIntegerField()),
            ],
            options={
                'db_table': 'neighborhood',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='UserNeighborhood',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'user_neighborhood',
                'managed': False,
            },
        ),
    ]
