# Generated by Django 4.0.2 on 2022-06-30 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='neighborhood',
            name='description',
            field=models.TextField(default='', null=True),
        ),
    ]
