# Generated by Django 4.0.2 on 2022-05-12 01:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='neighborhood',
            options={},
        ),
        migrations.AlterModelOptions(
            name='userneighborhood',
            options={},
        ),
    ]
