# Generated by Django 4.0.2 on 2022-07-11 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0002_alter_neighborhood_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='userneighborhood',
            name='rejected',
            field=models.SmallIntegerField(default=0),
        ),
    ]
