# Generated by Django 4.0.2 on 2022-07-25 22:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0003_userneighborhood_rejected'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='neighborhood',
            name='user',
        ),
    ]
