# Generated by Django 4.0.2 on 2022-07-31 18:56

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0004_remove_neighborhood_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='neighborhood',
            name='description',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='neighborhood',
            name='shape',
            field=django.contrib.gis.db.models.fields.MultiPolygonField(blank=True, default='', null=True, srid=4326),
        ),
    ]
