# Generated by Django 4.0.2 on 2022-06-04 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0004_neighborhood_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='neighborhood',
            name='description',
            field=models.TextField(default=''),
        ),
    ]
