# Generated by Django 4.0.2 on 2022-06-11 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0006_alter_neighborhood_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='neighborhood',
            name='description',
            field=models.TextField(default=''),
        ),
    ]
