# Generated by Django 4.0.2 on 2022-06-30 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0008_justification'),
    ]

    operations = [
        migrations.AddField(
            model_name='userneighborhood',
            name='justification',
            field=models.TextField(default=''),
        ),
    ]
