# Generated by Django 4.0.2 on 2022-06-30 02:44

import cloudinary.models
import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('registration', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PointOfInterest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=45)),
                ('location', django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ('description', models.TextField(default='')),
            ],
            options={
                'db_table': 'point_of_interest',
            },
        ),
        migrations.CreateModel(
            name='PointOfInterestImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', cloudinary.models.CloudinaryField(max_length=255, verbose_name='image')),
                ('description', models.TextField(default='')),
                ('point_of_interest', models.ForeignKey(db_constraint=False, null=True, on_delete=django.db.models.deletion.CASCADE, to='neighborhood.pointofinterest')),
            ],
            options={
                'db_table': 'point_of_interest_image',
            },
        ),
        migrations.CreateModel(
            name='NeighborhoodPointOfInterest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('neighborhood', models.ForeignKey(db_constraint=False, null=True, on_delete=django.db.models.deletion.CASCADE, to='registration.neighborhood')),
                ('point_of_interest', models.ForeignKey(db_constraint=False, null=True, on_delete=django.db.models.deletion.CASCADE, to='neighborhood.pointofinterest')),
            ],
            options={
                'db_table': 'neighborhood_point_of_interest',
            },
        ),
        migrations.CreateModel(
            name='NeighborhoodImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', cloudinary.models.CloudinaryField(max_length=255, verbose_name='image')),
                ('description', models.TextField(default='')),
                ('neighborhood', models.ForeignKey(db_constraint=False, null=True, on_delete=django.db.models.deletion.CASCADE, to='registration.neighborhood')),
            ],
            options={
                'db_table': 'neighborhood_image',
            },
        ),
    ]
