# Generated by Django 4.0.2 on 2022-06-04 15:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0003_alter_neighborhood_id'),
        ('neighborhood', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='neighborhoodphoto',
            name='neighborhood',
            field=models.ForeignKey(db_constraint=False, null=True, on_delete=django.db.models.deletion.CASCADE, to='registration.neighborhood'),
        ),
    ]
