# Generated by Django 4.0.2 on 2022-06-04 19:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('neighborhood', '0002_neighborhoodphoto_neighborhood'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='neighborhoodphoto',
            name='title',
        ),
    ]
