# Generated by Django 4.0.2 on 2022-06-07 00:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0005_neighborhood_description'),
        ('neighborhood', '0004_pointofinterest'),
    ]

    operations = [
        migrations.CreateModel(
            name='NeighborhoodPointOfInterest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('neighborhood', models.ForeignKey(db_constraint=False, null=True, on_delete=django.db.models.deletion.CASCADE, to='registration.neighborhood')),
                ('point_of_interest', models.ForeignKey(db_constraint=False, null=True, on_delete=django.db.models.deletion.CASCADE, to='neighborhood.pointofinterest')),
            ],
            options={
                'db_table': 'neighborhood_point_of_interest',
            },
        ),
    ]
