# Generated by Django 4.0.2 on 2022-06-09 22:12

import ckeditor.fields
import cloudinary.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0005_neighborhood_description'),
        ('neighborhood', '0006_post'),
    ]

    operations = [
        migrations.CreateModel(
            name='NeighborhoodImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', cloudinary.models.CloudinaryField(max_length=255, verbose_name='image')),
                ('description', models.TextField(default='')),
                ('neighborhood', models.ForeignKey(db_constraint=False, null=True, on_delete=django.db.models.deletion.CASCADE, to='registration.neighborhood')),
            ],
            options={
                'db_table': 'neighborhood_image',
            },
        ),
        migrations.AddField(
            model_name='pointofinterest',
            name='description',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='NeighborhoodPhoto',
        ),
    ]
