# Generated by Django 4.0.2 on 2022-06-09 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('neighborhood', '0008_alter_pointofinterest_description_delete_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='neighborhoodimage',
            name='description',
            field=models.CharField(max_length=45),
        ),
    ]
