# Generated by Django 4.0.2 on 2022-06-11 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('neighborhood', '0009_alter_neighborhoodimage_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='neighborhoodimage',
            name='description',
            field=models.TextField(default=''),
        ),
    ]
