# Generated by Django 4.0.2 on 2022-06-19 13:27

import cloudinary.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('neighborhood', '0010_alter_neighborhoodimage_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='PointOfInterestImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', cloudinary.models.CloudinaryField(max_length=255, verbose_name='image')),
                ('point_of_interest', models.ForeignKey(db_constraint=False, null=True, on_delete=django.db.models.deletion.CASCADE, to='neighborhood.pointofinterest')),
            ],
            options={
                'db_table': 'point_of_interest_image',
            },
        ),
    ]
