# Generated by Django 4.0.2 on 2022-06-22 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('neighborhood', '0011_pointofinterestimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='pointofinterestimage',
            name='description',
            field=models.TextField(default=''),
        ),
    ]
